// src/components/ResponsiveImg.jsx
//
// <picture> wrapper for images generated by scripts/build-page-images.mjs
// (naming convention: "{base}-{width}.{avif,webp}" next to the original).
//
// WHY THIS EXISTS: several dish/drink photos were being served as flat
// <img src="/menu/Vegetales.webp"> at their full camera resolution — 4775×
// 6614px / 7MB for a 150px carousel thumbnail. Every visitor downloaded the
// same file regardless of whether they were looking at a mobile thumbnail or
// the desktop lightbox. This is what PageSpeed's "Improve image delivery"
// audit was flagging (26.6MB of savings on mobile, from images alone).
//
// `sizes` is not optional — without it the browser assumes the image renders
// at 100vw and picks an oversized source from the srcSet regardless of how
// small it's actually displayed. Pass the REAL rendered width/breakpoints
// (see the call sites in MenuCarousel.jsx and menu/MenuParts.jsx for the
// values, each derived from that component's own CSS).
import manifest from "../data/imageManifest.json";

// Only used for images NOT in the manifest (i.e. never run through
// scripts/build-page-images.mjs). Every menu/drink photo IS in the manifest —
// see the comment below on why the manifest, not this constant, is what
// actually governs which widths get requested for those.
const DEFAULT_WIDTHS = [240, 480, 768, 1080, 1600];

function toBase(src) {
  return src.replace(/\.(webp|jpg|jpeg|png)$/i, "");
}

export default function ResponsiveImg({
  src,
  alt,
  sizes,
  widths,
  className,
  loading = "lazy",
  decoding = "async",
  onClick,
  style,
}) {
  const path = src.startsWith("/") ? src : `/${src}`;
  const base = toBase(path);

  // The manifest records what scripts/build-page-images.mjs ACTUALLY wrote,
  // per image — not what was asked for. `withoutEnlargement` there means a
  // source smaller than a requested tier silently produces FEWER files than
  // its job's `widths` list (e.g. a 640px-native source never gets a 768w
  // tier). Trusting a hardcoded ladder instead of the manifest is exactly
  // what broke "Ensenada Dreams" (its 640px source has no 768/1080/1600
  // tiers; the component picked one anyway, the request 404'd, the image
  // rendered as a broken-image icon). `widths` is only a fallback for images
  // that were never run through that pipeline at all.
  const realWidths = manifest[base];
  const effectiveWidths = realWidths ?? widths ?? DEFAULT_WIDTHS;

  const avifSrcSet = effectiveWidths.map((w) => `${base}-${w}.avif ${w}w`).join(", ");
  const webpSrcSet = effectiveWidths.map((w) => `${base}-${w}.webp ${w}w`).join(", ");
  // Mid-tier fallback for browsers that ignore <picture> entirely (none in
  // practice today, but the <img> still needs a valid standalone src) — from
  // the REAL list, so it can never point at a tier that was never written.
  const fallbackWidth =
    effectiveWidths[Math.min(2, effectiveWidths.length - 1)];

  return (
    // display:contents makes <picture> invisible to layout — it does not
    // affect the browser's source-selection algorithm, only box generation.
    // Without it, callers' percentage sizing (w-full h-full, common across
    // every call site here) has no definite ancestor to resolve against,
    // since <picture> is `display: inline` by default with no size of its
    // own: the <img> silently collapses to zero visible size even though it
    // loads correctly (complete: true, real naturalWidth) — this is exactly
    // the failure mode this component hit on its first render.
    <picture style={{ display: "contents" }}>
      <source type="image/avif" srcSet={avifSrcSet} sizes={sizes} />
      <source type="image/webp" srcSet={webpSrcSet} sizes={sizes} />
      <img
        src={`${base}-${fallbackWidth}.webp`}
        srcSet={webpSrcSet}
        sizes={sizes}
        alt={alt}
        loading={loading}
        decoding={decoding}
        className={className}
        onClick={onClick}
        style={style}
      />
    </picture>
  );
}
